# Generated by Django 3.2.3 on 2021-10-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopkeeper',
            name='image',
            field=models.ImageField(null=True, upload_to='shops/images'),
        ),
    ]
