# Generated by Django 3.2.3 on 2021-10-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_shopkeeper_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('contactNum', models.CharField(max_length=10, verbose_name='Phone Number')),
                ('deliveryAddress', models.TextField(verbose_name='Delivery Address')),
                ('password', models.CharField(max_length=30, verbose_name='Password')),
            ],
        ),
        migrations.RemoveField(
            model_name='shopkeeper',
            name='image',
        ),
        migrations.RemoveField(
            model_name='shopkeeper',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='shopkeeper',
            name='shop',
        ),
        migrations.AddField(
            model_name='shopkeeper',
            name='contactNum',
            field=models.CharField(default='0', max_length=10, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='shopkeeper',
            name='password',
            field=models.CharField(default='None', max_length=30, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='shopkeeper',
            name='resAddress',
            field=models.TextField(default='None', verbose_name='Residential Address'),
        ),
        migrations.AddField(
            model_name='shopkeeper',
            name='shopAddress',
            field=models.TextField(default='None', verbose_name='Shop Address'),
        ),
        migrations.AddField(
            model_name='shopkeeper',
            name='shopName',
            field=models.CharField(default='None', max_length=100, verbose_name='Shop Name'),
        ),
        migrations.AlterField(
            model_name='shopkeeper',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='shopkeeper',
            name='name',
            field=models.CharField(default='None', max_length=100, verbose_name='Full Name'),
        ),
    ]
