# Generated by Django 3.2.8 on 2021-10-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='price',
            field=models.IntegerField(default=100),
        ),
    ]
