# Generated by Django 3.2.8 on 2021-10-18 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_requests_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('shop', models.CharField(max_length=1000)),
                ('item', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('requestId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.requests')),
            ],
        ),
    ]
