# Generated by Django 3.2.8 on 2021-10-18 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_responses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responses',
            name='requestId',
        ),
    ]
