# Generated by Django 3.2.8 on 2021-10-18 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_responses_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasResponded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.requests')),
            ],
        ),
    ]
