# Generated by Django 3.2.8 on 2021-10-18 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_hasresponded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hasresponded',
            old_name='request',
            new_name='req',
        ),
    ]
