# Generated by Django 3.2.8 on 2021-10-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_request_hasresponded_req'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='price',
            field=models.IntegerField(),
        ),
    ]
