# Generated by Django 3.2.8 on 2021-10-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_items_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='requests',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
