# Generated by Django 3.2.8 on 2021-10-19 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20211018_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responses',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='responses',
            name='item',
        ),
        migrations.RemoveField(
            model_name='responses',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='responses',
            name='type',
        ),
        migrations.AddField(
            model_name='responses',
            name='req',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.requests'),
        ),
    ]
