# Generated by Django 3.2.8 on 2021-10-19 17:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20211019_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('shop', models.CharField(max_length=1000)),
                ('shopkeeper', models.CharField(max_length=1000)),
                ('item', models.CharField(max_length=1000)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='responses',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
