# Generated by Django 3.2.8 on 2021-10-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20211019_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastorders',
            name='returnItem',
            field=models.BooleanField(default=False),
        ),
    ]
