# Generated by Django 3.2.8 on 2021-10-23 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20211023_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.items'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.shopkeeper'),
        ),
    ]
