# Generated by Django 3.2.8 on 2021-10-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20211023_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastorders',
            name='reason',
            field=models.TextField(null=True),
        ),
    ]
