# Generated by Django 3.2.8 on 2021-10-31 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211019_0341'),
        ('home', '0022_pastorders_reason'),
    ]

    operations = [
    ]
