# Generated by Django 3.2.8 on 2021-10-31 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_merge_0004_auto_20211019_0341_0022_pastorders_reason'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.RenameField(
            model_name='shopkeeper',
            old_name='shopName',
            new_name='shop',
        ),
    ]
