# Generated by Django 3.2.8 on 2021-10-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20211031_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopkeeper',
            name='contactNum',
        ),
        migrations.RemoveField(
            model_name='shopkeeper',
            name='password',
        ),
        migrations.RemoveField(
            model_name='shopkeeper',
            name='resAddress',
        ),
        migrations.RemoveField(
            model_name='shopkeeper',
            name='shopAddress',
        ),
        migrations.AddField(
            model_name='shopkeeper',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shops/images'),
        ),
        migrations.AddField(
            model_name='shopkeeper',
            name='phone',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='shopkeeper',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='shopkeeper',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='shopkeeper',
            name='shop',
            field=models.CharField(max_length=1000),
        ),
    ]
