# Generated by Django 3.2.8 on 2021-11-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20211031_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('contactNum', models.CharField(max_length=10, verbose_name='Phone Number')),
                ('deliveryAddress', models.TextField(verbose_name='Delivery Address')),
                ('password', models.CharField(max_length=30, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default='Change It', max_length=100, verbose_name='Customer Name')),
                ('item_name', models.CharField(max_length=50, verbose_name='Item Name')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('item_price', models.FloatField(max_length=10, verbose_name='Current Price')),
                ('shopkeeper_name', models.CharField(default='Change It', max_length=100, verbose_name='Shopkeeper Name')),
                ('shop_name', models.CharField(default='Change It', max_length=100, verbose_name='Shop Name')),
                ('date', models.DateTimeField(verbose_name='Order Time')),
            ],
        ),
    ]
